# redis configuration
host: 'localhost'
port: 6379
defaultDatabaseIndex: 0

usePassword: false
password: 'setUsePasswordToTrue'

# chunk I/O (blocks) configuration
chunkService:
  databaseIndex: 0
  readOnly: false
